---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sirp7472/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan optimize:clear
